package com.restaurant.factory;

import com.restaurant.model.MenuItem;

public class MenuItemFactory {
    // Factory method to create MenuItem
    public static MenuItem createMenuItem(String name, String category, double price) {
        return new MenuItem(0, name, category, price);  // Assuming ID is auto-generated by the database
    }

    public static MenuItem createMenuItem(int aInt, String string, String string0, double aDouble) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}